### ISSUE TITLE
Use default layout when displaying the fallback page template

### ISSUE THREAD

**Issue by drewbaker** [drewbaker/wp-easy#17]
Currently the fallback `/index.php` file doesn't use the `/layouts/default.php` file... Would be better if it did I think. I could be talked out of this as a bad idea...

My goal with WP Easy is you should be able to use it without the Router... So you could use it just for the SFC feature set and use the default WordPress template hierarchy. So perhaps forcing the use of default layout would prevent this?

**Comment by drewbaker** [comment]
I think we should update the plugin so that if there is no `router.php` file found, then it just uses normal WordPress template hierarchy. I suspect it already does that.

Then I think the fallback `/index.php` should also use the default layout if possible.

**Comment by rsm0128** [comment]
@drewbaker When `router.php` is missing in the theme directory, it works as normal WordPress template already.
