### ISSUE TITLE
Enable URL query parameters in router

### ISSUE THREAD

**Issue by lwaldner** [drewbaker/wp-easy#21]
Problem: When using url query parameters the router considers the query parameters apart of the url path structure. For example the router matches the path /products/?category=balanced to the template "/products/:product/".

The router should ignore query parameters in the url when matching the url path to a rule in the routes table. For example /products/?category=balanced would match the template "/products/" and not "/products/:product/"

**Comment by drewbaker** [comment]
Yeah! Ok I think the fix would be in the plugin router function, before it does the PathToRegex function to just explode() on the ?, then send the first chunk to PathToRegex. 

Will try to get a fix to you in the next few days. But if you want a temp fix, try out the above. If it works, would be sweet if you made a PR!

**Comment by rsm0128** [comment]
@lwaldner I created a [PR](https://github.com/drewbaker/wp-easy/pull/22) to fix this issue and it's merged into main branch. Please check if it solves the issue.
