### ISSUE TITLE
Helper util to set HTML attribute

### ISSUE THREAD

**Issue by drewbaker** [drewbaker/wp-easy#26]
Today I had to add a controls attribute to a html video element. Would be helpful to have a util function that outputted “controls” if param is true. Like set_attribute(‘controls’, true).

**Comment by rsm0128** [comment]
@drewbaker I'm not clear with the requirement. Could you provide me the detail, please?

**Comment by drewbaker** [comment]
I want to be able to do this:

```
<video <?= set_attr('controls', true); ?> />
<video <?= set_attr('controls', false); ?> />
```

And it would output this:
```
<video controls />
<video/>
```

So a simple function that outputs the first param if the second param is true, if it's false it does nothing.
