### ISSUE TITLE
Move all compiled scripts and styles to be outside theme folder

### ISSUE THREAD

**Issue by drewbaker** [drewbaker/wp-easy#32]
Having all the compiled CSS and JS files get placed into the theme folder makes git commits very difficult. 

It would be better to create a temp directory in `/wp-content/wp-easy-dist` or something like that so that compiled files are kept away form the source files.

**Comment by drewbaker** [comment]
@rickpbaker keep an eye on this

**Comment by rsm0128** [comment]
We can use .gitignore to ignore the compiled css and js files. Let me update it

**Comment by drewbaker** [comment]
No I would rather them not be in the theme regardless. That’s how SCSS Lib worked and I think it’s a better idea.
