### ISSUE TITLE
Media query's still not working

### ISSUE THREAD

**Issue by drewbaker** [drewbaker/wp-easy#33]
Still seeing that media-queries aren't working, seems like the compiled CSS is not working.

![Screenshot 2024-10-09 at 3 38 38 PM](https://github.com/user-attachments/assets/c4809613-ac9d-4cd6-bb41-f644e08e229d)

![Screenshot 2024-10-09 at 3 40 38 PM](https://github.com/user-attachments/assets/fe2e3400-c4cb-4be4-a78c-138d5db52a18)

**Comment by drewbaker** [comment]
@rickpbaker keep an eye on this

**Comment by rsm0128** [comment]
As we discussed in Slack, it's not an issue with this plugin code. In my opinion, SCSS code might have some issues and that's why compilation didn't work well.

**Comment by drewbaker** [comment]
Is there any way to throw and error on compilation failure? Very confusing to just have it not work with no idea why.
