### ISSUE TITLE
Use <template> in SFC

### ISSUE THREAD

**Issue by drewbaker** [drewbaker/wp-easy#8]
Would love to replicate the Vue SFC syntax of `<template>` wrapping all the HTML in a component.

So a layout/template/component would become:

```
<?php // Some PHP code here, like setup of $args ?>

<template>
<div class="foo">Template html here</div>
</template>

<style>
.foo {
    color: red;
}
</style>

<script>
console.log('foo loaded')
</script>
```

**Comment by rsm0128** [comment]
@drewbaker In the [PR](https://github.com/drewbaker/wp-easy/pull/11), I added `<template>` tag support.

Also, I made the style and script parsed for template files as well.
For layout files, I think it's better don't parse them. The files have `wp_head()` and `wp_footer()` function which print external CSS and JS links. I think we already have a discussion on it and it was the reason that we made layout.
