### ISSUE TITLE
Auto import the /styles/media-queries.scss?

### ISSUE THREAD

**Issue by drewbaker** [drewbaker/wp-easy#9]
As It basically gets used everywhere, it would be great to auto import the `/styles/media-queries.scss` file into all SCSS files.

Perhaps the best way is to have a naming convention, like `global-media-queries.scss` makes it such that anything with `global-` get injected into all SCSS files?

Probably would happen in this function is my guess?
```
	public static function enqueue_component_styles($styles)
	{
		$diff = array_diff($styles, self::$printed_styles);
		if (! empty($diff)) {
			$style_str = join(PHP_EOL, $diff);
			$style_str = self::compile_scss($style_str);
			printf('<style>%s</style>', $style_str);

			self::$printed_styles = array_unique(array_merge(self::$printed_styles, $styles));
		}
	}
```	

I'd guess this is a built in feature to the SCSS Library, but would require a big refactor probably...

**Comment by rsm0128** [comment]
@drewbaker I fixed this problem in this commit. https://github.com/drewbaker/wp-easy/pull/11/commits/c65e6734bf1d7c2aa5f447528996ebab9c095b42

All the SCSS files in `/styles/base/` directory can be imported in component and template files.
Just import the SCSS file with file name only. (Don't need to indicate the directory as the /styles/base directory is looked)

```
<style>
    **@import 'media-queries';**

    .template-home {
        background-color: red;

        // Media queries can be used like this
        @media #{$lt-phone} {
            background-color: blue;
        }
    }
</style>
```
